version: 0.2
phases:
  build:
    commands:
      - scho Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/hello.jar
  discard-paths: yes